// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyxIReK7sR7q34qZjJWlQJ_9nh2cqDco',
    appId: '1:399204727957:web:06fd57c45c8c9c94846f9c',
    messagingSenderId: '399204727957',
    projectId: 'chatapp-5b60f',
    authDomain: 'chatapp-5b60f.firebaseapp.com',
    storageBucket: 'chatapp-5b60f.appspot.com',
    measurementId: 'G-B8RB0WFT20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzaU0O4NtKlpZb0bNYFYwvnUnMTJY-2U',
    appId: '1:399204727957:android:3e1f4c72f728bc96846f9c',
    messagingSenderId: '399204727957',
    projectId: 'chatapp-5b60f',
    storageBucket: 'chatapp-5b60f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuacNbin-2zFG6QxrwsLGsJieEsPWmaI',
    appId: '1:399204727957:ios:40ca9ed8e7d9aea7846f9c',
    messagingSenderId: '399204727957',
    projectId: 'chatapp-5b60f',
    storageBucket: 'chatapp-5b60f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuacNbin-2zFG6QxrwsLGsJieEsPWmaI',
    appId: '1:399204727957:ios:40ca9ed8e7d9aea7846f9c',
    messagingSenderId: '399204727957',
    projectId: 'chatapp-5b60f',
    storageBucket: 'chatapp-5b60f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
